### ISSUE TITLE
Dataset zip file not opening in Windows

### ISSUE THREAD

**Issue by Seleniumviper** [vanajmoorthy/CS4099-PolyTab#1]
I am attempted to unzip the dataset, but I am getting the error: Windows cannot open the zip file when I try to extract.
Please see attached file
![unzip](https://github.com/vanajmoorthy/CS4099-PolyTab/assets/168735159/0ea10ec1-c8e0-40a6-b5de-de55ae8d957a)

Any assistance will be helpful

**Comment by vanajmoorthy** [comment]
Hi, the dataset can be found here if the download link provided in the readme isn't working. Good luck!
https://github.com/marl/GuitarSet
